db_data:
    image: mysql:5.5
    entrypoint: /bin/bash
db:
    build: docker_sql/
    volumes_from:
        - db_data
    restart: always
web:
    build: .
    ports:
        - "80:80"
        - "81:81"
    links:
        - db:db
    restart: always
